version: '3.4'

services:
  geocode-service:
    image: geocode-service
    container_name: geocode-service
    build:
      context: ./geolocation
      dockerfile: ./Dockerfile
    ports:
      - "8081:8081"
  customer-service:
    container_name: customer-service
    image: customer-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    depends_on:
      - geocode-service
      - postgres-db
    environment:
      DB_HOST: postgres-db
      DB_USER: customerdbuser
      DB_PASS: customerdbuser1234
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: customerdbuser
      POSTGRES_PASSWORD: customerdbuser1234
      POSTGRES_DB: customerdb
    ports:
      - 5432:5432